// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk_PDkhWOIRhninR55J_QLP3D3gJ6LIVw',
    appId: '1:202206364413:web:939bb5058c0ec013197494',
    messagingSenderId: '202206364413',
    projectId: 'qrifyme-222bc',
    authDomain: 'qrifyme-222bc.firebaseapp.com',
    storageBucket: 'qrifyme-222bc.appspot.com',
    measurementId: 'G-1BN05NKY53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_zP-FCcMRNNRM52paoPE2iGTIS-Em_p4',
    appId: '1:202206364413:android:7eb1aab74db75186197494',
    messagingSenderId: '202206364413',
    projectId: 'qrifyme-222bc',
    storageBucket: 'qrifyme-222bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsQ5N7Pd7u5q4R3haOKS2AcoYVO7WRUSg',
    appId: '1:202206364413:ios:4b9fc9d56eb98096197494',
    messagingSenderId: '202206364413',
    projectId: 'qrifyme-222bc',
    storageBucket: 'qrifyme-222bc.appspot.com',
    iosBundleId: 'com.example.qrifyme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsQ5N7Pd7u5q4R3haOKS2AcoYVO7WRUSg',
    appId: '1:202206364413:ios:9288bfcaa3995abc197494',
    messagingSenderId: '202206364413',
    projectId: 'qrifyme-222bc',
    storageBucket: 'qrifyme-222bc.appspot.com',
    iosBundleId: 'com.example.qrifyme.RunnerTests',
  );
}
